//
// Generated file, do not edit! Created by opp_msgc 4.5 from messages/schedulerSelfMessage.msg.
//

#ifndef _SCHEDULERSELFMESSAGE_M_H_
#define _SCHEDULERSELFMESSAGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0405
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "hsrDefines.h"
// }}



/**
 * Class generated from <tt>messages/schedulerSelfMessage.msg</tt> by opp_msgc.
 * <pre>
 * message SchedulerSelfMessage 
 * {    
 * 	   SendData sendData;
 * }
 * </pre>
 */
class SchedulerSelfMessage : public ::cMessage
{
  protected:
    SendData sendData_var;

  private:
    void copy(const SchedulerSelfMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SchedulerSelfMessage&);

  public:
    SchedulerSelfMessage(const char *name=NULL, int kind=0);
    SchedulerSelfMessage(const SchedulerSelfMessage& other);
    virtual ~SchedulerSelfMessage();
    SchedulerSelfMessage& operator=(const SchedulerSelfMessage& other);
    virtual SchedulerSelfMessage *dup() const {return new SchedulerSelfMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual SendData& getSendData();
    virtual const SendData& getSendData() const {return const_cast<SchedulerSelfMessage*>(this)->getSendData();}
    virtual void setSendData(const SendData& sendData);
};

inline void doPacking(cCommBuffer *b, SchedulerSelfMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, SchedulerSelfMessage& obj) {obj.parsimUnpack(b);}


#endif // _SCHEDULERSELFMESSAGE_M_H_
