//
// Generated file, do not edit! Created by opp_msgc 4.5 from messages/cpuSelfMessage.msg.
//

#ifndef _CPUSELFMESSAGE_M_H_
#define _CPUSELFMESSAGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0405
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "hsrDefines.h"
// }}



/**
 * Class generated from <tt>messages/cpuSelfMessage.msg</tt> by opp_msgc.
 * <pre>
 * message cpuSelfMessage 
 * {    
 * 	   SendData sendData;
 * }
 * </pre>
 */
class cpuSelfMessage : public ::cMessage
{
  protected:
    SendData sendData_var;

  private:
    void copy(const cpuSelfMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const cpuSelfMessage&);

  public:
    cpuSelfMessage(const char *name=NULL, int kind=0);
    cpuSelfMessage(const cpuSelfMessage& other);
    virtual ~cpuSelfMessage();
    cpuSelfMessage& operator=(const cpuSelfMessage& other);
    virtual cpuSelfMessage *dup() const {return new cpuSelfMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual SendData& getSendData();
    virtual const SendData& getSendData() const {return const_cast<cpuSelfMessage*>(this)->getSendData();}
    virtual void setSendData(const SendData& sendData);
};

inline void doPacking(cCommBuffer *b, cpuSelfMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, cpuSelfMessage& obj) {obj.parsimUnpack(b);}


#endif // _CPUSELFMESSAGE_M_H_
