//
// Generated file, do not edit! Created by opp_msgc 4.5 from messages/hsrMessage.msg.
//

#ifndef _HSRMESSAGE_M_H_
#define _HSRMESSAGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0405
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>messages/hsrMessage.msg</tt> by opp_msgc.
 * <pre>
 * packet hsrMessage 
 * {
 *     unsigned int path; 
 *     unsigned int sequencenumber; 
 *     unsigned int lsdu_size; 
 *     
 *     int nextEtherType;
 *     int ownEtherType = 0x88FB; 
 *     
 *     
 * }
 * </pre>
 */
class hsrMessage : public ::cPacket
{
  protected:
    unsigned int path_var;
    unsigned int sequencenumber_var;
    unsigned int lsdu_size_var;
    int nextEtherType_var;
    int ownEtherType_var;

  private:
    void copy(const hsrMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const hsrMessage&);

  public:
    hsrMessage(const char *name=NULL, int kind=0);
    hsrMessage(const hsrMessage& other);
    virtual ~hsrMessage();
    hsrMessage& operator=(const hsrMessage& other);
    virtual hsrMessage *dup() const {return new hsrMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned int getPath() const;
    virtual void setPath(unsigned int path);
    virtual unsigned int getSequencenumber() const;
    virtual void setSequencenumber(unsigned int sequencenumber);
    virtual unsigned int getLsdu_size() const;
    virtual void setLsdu_size(unsigned int lsdu_size);
    virtual int getNextEtherType() const;
    virtual void setNextEtherType(int nextEtherType);
    virtual int getOwnEtherType() const;
    virtual void setOwnEtherType(int ownEtherType);
};

inline void doPacking(cCommBuffer *b, hsrMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, hsrMessage& obj) {obj.parsimUnpack(b);}


#endif // _HSRMESSAGE_M_H_
